"""Initial schema with passowrd_hash

Revision ID: 5fae8870072a
Revises: 
Create Date: 2026-01-22 07:56:08.903150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fae8870072a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='user email address used for login'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='bcrypt hashed password'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='account created timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='last update timestamp'),
    sa.CheckConstraint("email ~* '^[A-Za-z0-9._%%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,}$'", name='valid_email_format'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('audio_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='owner user id - cascades on delete'),
    sa.Column('title', sa.String(length=255), nullable=False, comment="Audio title (e.g., Surah Al-Baqarah'')"),
    sa.Column('author', sa.String(length=255), nullable=False, comment='author name'),
    sa.Column('category', sa.Enum('QURAN', 'LECTURE', 'REMINDER', name='audiocategory'), nullable=False, comment='audio category type'),
    sa.Column('description', sa.Text(), nullable=True, comment='optinal audio descripton'),
    sa.Column('file_url', sa.Text(), nullable=False, comment='S3 cloud storage url'),
    sa.Column('duration', sa.Integer(), nullable=True, comment='duration in seconds'),
    sa.Column('file_size', sa.BigInteger(), nullable=True, comment='file size in bytes'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='upload timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='last metadata update timestamp'),
    sa.CheckConstraint('duration > 0', name='positive_duration'),
    sa.CheckConstraint('file_size > 0', name='positive_file_size'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audio_author', 'audio_files', ['author'], unique=False)
    op.create_index('idx_audio_title', 'audio_files', ['title'], unique=False)
    op.create_index('idx_audio_user_category', 'audio_files', ['user_id', 'category'], unique=False)
    op.create_index('idx_audio_user_created', 'audio_files', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audio_files_author'), 'audio_files', ['author'], unique=False)
    op.create_index(op.f('ix_audio_files_category'), 'audio_files', ['category'], unique=False)
    op.create_index(op.f('ix_audio_files_created_at'), 'audio_files', ['created_at'], unique=False)
    op.create_index(op.f('ix_audio_files_id'), 'audio_files', ['id'], unique=False)
    op.create_index(op.f('ix_audio_files_title'), 'audio_files', ['title'], unique=False)
    op.create_index(op.f('ix_audio_files_user_id'), 'audio_files', ['user_id'], unique=False)
    op.create_table('playlists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='owner user ID - cascades on delete'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='playlist name'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='playlist creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='last update timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_playlist_name', 'playlists', ['name'], unique=False)
    op.create_index('idx_playlist_user', 'playlists', ['user_id'], unique=False)
    op.create_index(op.f('ix_playlists_id'), 'playlists', ['id'], unique=False)
    op.create_index(op.f('ix_playlists_user_id'), 'playlists', ['user_id'], unique=False)
    op.create_table('playlist_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False, comment='playlist id - cascades on delete'),
    sa.Column('audio_id', sa.Integer(), nullable=False, comment='audio file ID - cascades on delete'),
    sa.Column('order', sa.Integer(), nullable=False, comment='position in playlist for sorting'),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='timestamp when added to playist'),
    sa.CheckConstraint('"order" >= 0', name='non_negative_order'),
    sa.ForeignKeyConstraint(['audio_id'], ['audio_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_playlist_items_playlist', 'playlist_items', ['playlist_id', 'order'], unique=False)
    op.create_index('idx_unique_playlist_audio', 'playlist_items', ['playlist_id', 'audio_id'], unique=True)
    op.create_index(op.f('ix_playlist_items_audio_id'), 'playlist_items', ['audio_id'], unique=False)
    op.create_index(op.f('ix_playlist_items_id'), 'playlist_items', ['id'], unique=False)
    op.create_index(op.f('ix_playlist_items_playlist_id'), 'playlist_items', ['playlist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playlist_items_playlist_id'), table_name='playlist_items')
    op.drop_index(op.f('ix_playlist_items_id'), table_name='playlist_items')
    op.drop_index(op.f('ix_playlist_items_audio_id'), table_name='playlist_items')
    op.drop_index('idx_unique_playlist_audio', table_name='playlist_items')
    op.drop_index('idx_playlist_items_playlist', table_name='playlist_items')
    op.drop_table('playlist_items')
    op.drop_index(op.f('ix_playlists_user_id'), table_name='playlists')
    op.drop_index(op.f('ix_playlists_id'), table_name='playlists')
    op.drop_index('idx_playlist_user', table_name='playlists')
    op.drop_index('idx_playlist_name', table_name='playlists')
    op.drop_table('playlists')
    op.drop_index(op.f('ix_audio_files_user_id'), table_name='audio_files')
    op.drop_index(op.f('ix_audio_files_title'), table_name='audio_files')
    op.drop_index(op.f('ix_audio_files_id'), table_name='audio_files')
    op.drop_index(op.f('ix_audio_files_created_at'), table_name='audio_files')
    op.drop_index(op.f('ix_audio_files_category'), table_name='audio_files')
    op.drop_index(op.f('ix_audio_files_author'), table_name='audio_files')
    op.drop_index('idx_audio_user_created', table_name='audio_files')
    op.drop_index('idx_audio_user_category', table_name='audio_files')
    op.drop_index('idx_audio_title', table_name='audio_files')
    op.drop_index('idx_audio_author', table_name='audio_files')
    op.drop_table('audio_files')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
